version: '3.9'
volumes:
    inventory-service-data:
    beer-service-data:
    beerorder-service-data:

services:
    elasticsearch:
        image: elasticsearch:7.9.0
        ports:
            - 9200:9200
        environment:
            discovery.type: single-node

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.0
        ports:
            - 5601:5601
        restart: on-failure
        depends_on:
            - elasticsearch

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.9.0
        command: filebeat -e -strict.perms=false
        volumes:
            - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        user: root
        restart: on-failure
        depends_on:
            - elasticsearch

    jms:
        image: vromero/activemq-artemis
        ports:
            - 8161:8161

    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411

    eureka:
        image: mssc-beerworks-service-registry:${TAG}
        depends_on:
            - zipkin
        ports:
            - 8761:8761
        env_file:
            - ./mysql.env
            - ./cloudconfig.env

    configserver:
        image: mssc-beerworks-config-service:${TAG}
        depends_on:
            - eureka
        ports:
            - 8888:8888
        env_file:
            - ./cloudconfig.env
        environment:
            - EUREKA_INSTANCE_PREFERIPADDRESS=true
#            - logging_config=

    inventory-service-db:
        image: mysql:8
        ports:
            - 3308:3306
        environment:
            - MYSQL_DATABASE=inventory-service
            - MYSQL_USER=inventory-service
        env_file: ./mysql.env
        volumes:
            - inventory-service-data:/var/lib/mysql
        deploy:
            resources:
                limits:
                    memory: 150m
                    cpus: 1

    inventory-service:
        image: griezma/mssc-beer-inventory-service:${TAG}
        depends_on:
            - eureka
            - configserver
#            - inventory-service-db
            - jms
        ports:
            - 8081:8081
        env_file:
            - ./cloudconfig.env
            - ./h2db.env
        environment:
            - mysql_host=inventory-service-db
#            - logging_config=
#            - logging_level_org_springframework_cloud=debug
        restart: on-failure
        labels:
            collect_logs_with_filebeat: "true"
#        deploy:
#            resources:
#                limits:
#                    memory: 150m
#                    cpus: 1

    inventory-failover:
        image: griezma/mssc-beer-inventory-failover:${TAG}
        depends_on:
            - eureka
        ports:
            - 8083:8083
        env_file:
            - ./cloudconfig.env
        deploy:
            resources:
                limits:
                    memory: 150m
                    cpus: 1

    beer-service-db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=beer-service
            - MYSQL_USER=beer-service
        env_file: ./mysql.env
        volumes:
            - beer-service-data:/var/lib/mysql
        deploy:
            resources:
                limits:
                    memory: 150m
                    cpus: 1

    beer-service:
        image: griezma/mssc-beer-service:${TAG}
        depends_on:
            - eureka
            - configserver
            - jms
#            - beer-service-db
            - inventory-service
        ports:
            - 8080:8080
        env_file:
            - ./cloudconfig.env
            - ./h2db.env
        environment:
            - MYSQL_HOST=beer-service-db
#            - logging_config=
        restart: on-failure
#        deploy:
#            resources:
#                limits:
#                    memory: 150m
#                    cpus: 1

    beerorder-service-db:
        image: mysql:8
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABASE=beerorder-service
            - MYSQL_USER=beerorder-service
        env_file: ./mysql.env
        volumes:
            - beerorder-service-data:/var/lib/mysql
        deploy:
            resources:
                limits:
                    memory: 150m
                    cpus: 1

    beer-order-service:
        image: griezma/mssc-beer-order-service:${TAG}
        depends_on:
            - eureka
            - configserver
            - jms
#            - beerorder-service-db
            - beer-service
        ports:
            - 8082:8082
        env_file:
            - ./cloudconfig.env
            - ./h2db.env
        environment:
            - MYSQL_HOST=beerorder-service-db
            - BEERSERVICE_HOST=beer-service
#            - logging_config=
        restart: on-failure
        deploy:
            resources:
                limits:
                    memory: 150m
                    cpus: 1

    gateway:
        image: mssc-beerworks-gateway:${TAG}
        depends_on:
            - eureka
            - kibana
            - filebeat
            - inventory-service
#            - inventory-failover
#            - beer-service
#            - beer-order-service
        ports:
            - 9090:9090
        env_file:
            - ./cloudconfig.env
        environment:
            - foo=
#            - logging_config=
        labels:
            collect_logs_with_filebeat: "true"